### ISSUE TITLE
Use new report format to drive high-level QC reporting display

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#56] opened 2018-08-15 23:03 UTC
On the completion of https://github.com/biolink/ontobio/issues/219 and its output in the pipeline, we'd like to use it to drive two new displays: rules on one axis, groups/species on the other, and max known violations per cell.

Once we have this minimal product, we will iterate on details of the display.

Tagging @dougli1sqrd and @cmungall

**Comment by dougli1sqrd** [comment] 2018-08-28 18:10
Some details about how this will look:
Table with Group name along the top horizontally, and the Rule ID along the left side of the table. Inside each cell will be the number of violations of each group for a certain rule.

Each group name is a hyperlink, and each number in a cell is a hyperlink. 

Group Link:
The group link will go to a group error summary page.
GAF date, pipeline process date, Group Name and dataset name?
Number of annotations, number skipped, etc.
Table of contents for Rules, with hyperlinks to the section with the rule messages. 
Then a header for each rule, with the gaf line and specific message listed.

Number Link:
Link to the group page above, at the location of the page where that rule is described.

**Comment by dougli1sqrd** [comment] 2018-08-28 18:36
Duplicate of: https://github.com/geneontology/go-site/issues/709

**Closed by dougli1sqrd** 2018-08-28 18:36 UTC
Labels: enhancement
