### ISSUE TITLE
Remove robot build as part of pipeline

### ISSUE THREAD

**Issue by cmungall** [geneontology/pipeline#12] opened 2017-12-20 21:34 UTC
https://github.com/ontodev/robot/issues/211

**Comment by dougli1sqrd** [comment] 2018-01-10 22:03
This is blocked on https://github.com/ontodev/robot/issues/211 still. I think all we need to do is make a release of robot into sonatype/maven

**Comment by kltm** [comment] 2018-01-10 22:09
Plus 1) add in the variables to the pipeline, 2) get the downloader setup, and 3) added into either the step bin or the "global" bin.

**Comment by kltm** [comment] 2018-02-13 01:14
After a little discussion with @cmungall and @dougli1sqrd , we've decided that while important this is not a pressing need for the minimal released pipeline.

**Comment by cmungall** [comment] 2018-02-23 18:58
Shall we switch the ontology pipeline to use the osk Docker image?

https://github.com/INCATools/ontology-starter-kit/issues/22

**Comment by kltm** [comment] 2018-02-23 22:18
If the tool is being called on the command line from the Makefile, I'm not sure how that would make things easier unless it is dropping the bin on disk. We could run the Makefile from within the docker environment, but I think that would probably be more confusing than what we have now.

**Comment by kltm** [comment] 2019-01-22 23:38
Is ROBOT used anywhere besides the go-ontology build ontology step? If not, this is superseded by #76 and can be closed.

**Comment by cmungall** [comment] 2019-01-23 05:52
Check with Eric, may be used to prep data for blazegraph

**Comment by dougli1sqrd** [comment] 2019-01-23 19:21
Yes, it seems we no longer use robot in the megastep. I forget what we used to use it for. There are no references to robot in the makefile.

**Comment by kltm** [comment] 2019-01-23 20:11
Hijacking ticket for removal--otherwise a dupe of #76

**Closed** 2022-02-17 18:35 UTC
Labels: enhancement
